#family:
#  family-name: happy
#  father: ${father.name}
#  mother: Rose
#  child: Tom
#  age: ${random.int(1,30)}
#father:
#  name: 张三

server:
  host: localhost
  port: 8080
  context-path: /api
person:
  first-name: ${first-name.name:John}
  last-name: ${last-name.name:Doe}
  age: ${random.int(20,50)}
  id: ${random.uuid}
  phone: ${phone.number:1234567890}

student:
  name: 张小飞
  age: 20
  happy: true
  birth: 2004/01/01
  map: {k1: v1 , k2: v2}
  list:
    - code
    - read
    - music
  dog:
    name: 虎子
    age: 11

#需要使用的配置文件


db:
  url: jdbc:mysql://localhost:3306/spring_boot?useSSL=false&serverTimezone=UTC
  username: root
  password: zjw20040929
  driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
 secret: mySecretKey
# JWT密钥
 expiration: 3600000 # 1小时，单位为毫秒



custom:
  qrcode:
    content: "https://www.baidu.com"
  log:
    level: "INFO"
  backup:
    location: E:/log

spring:
  mail:
    host: smtp.qq.com
    username: 2983532292@qq.com
    password: xkerjtmlqryzdfie
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  profiles:
    active: test

